baseurl = "http://wyb0.com"
languageCode = "en-us"
copyright = "&copy; 2016-2017 Reber. All Rights Reserved."
canonifyurls = true



[indexes]
    tag = "tags"
    topic = "topics"

[Params]
    Logo = "<img src='/img/logo.png' width='70px'>" #Reber's Blog
    Author = "reber"
    Paginate = 10
    DateFormat = "2006-01-02"

    [Params.Social]
        GitHub = "reber-9"
        WeiboID = "5819760166"

    [Params.Strings]
        Search = "Search" #搜索
        Categories = "Categories" #分类
        Archive = "Archive" #归档
        Tags = "Tags" #标签
        TagCloud = "TagCloud" #标签云
        Links = "Links" #友链

[Menu]
    [[Menu.Main]]
        name = "Home"
        pre = "<i class='fa fa-home fa-fw'></i>"
        weight = 1
        identifier = "home"
        url = "/"
    [[Menu.Main]]
        name = "Archive"
        pre = "<i class='fa fa-list fa-fw'></i>"
        weight = 2
        identifier = "posts"
        url = "/posts/"
    [[Menu.Main]]
        name = "About"
        pre = "<i class='fa fa-user fa-fw'></i>"
        weight = 3
        identifier = "about"
        url = "/about/"

